Moved Netlify manual job to circleci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -54,6 +54,44 @@ jobs:
           name: Print urls to log
           command: |
             cat broken_external_urls.txt
+  
+  netlify_manual:
+    docker:
+      - image: cimg/node:14.21.3-browsers
+    resource_class: xlarge
+    steps:
+      - run:
+          name: Has secrets?
+          command: |
+            if [ -z "$NETLIFY_AUTH_TOKEN" ] || [ -z "$NETLIFY_SITE_ID" ]; then
+              echo "Missing required secrets."
+              exit 1
+            fi
+      # Step to cancel workflow
+      - run:
+          name: Cancel workflow if failure
+          command: |
+            if [ "$CIRCLE_JOB" != "netlify_manual" ]; then
+              curl -X POST https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel -H "Circle-Token: ${CIRCLE_API_TOKEN}"
+            fi
+          when: on_fail
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            yarn install --frozen-lockfile
+      - run:
+          name: Build preview
+          command: |
+            yarn build
+      - run:
+          name: Install Netlify CLI
+          command: |
+            npm install netlify-cli -g
+      - run:
+          name: Deploy preview to Netlify
+          command: |
+            netlify deploy --filter @okta/vuepress-site
 
 orbs:
   general-platform-helpers: okta/general-platform-helpers@1.8
@@ -92,5 +130,5 @@ workflows:
   netlify_manual:
     when: << pipeline.parameters.trigger_netlify_manual >>
     jobs:
-      - node_build_checks:
-          name: "TODO:Run Netlify Manual"
+      - netlify_manual:
+          name: "Netlify Manual"
